#mysql数据库连接
server:
  port: 8000
mybatis-plus: #mybatis
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#指定文件的路径  mapper-locations: classpath:com/atguigu/srb/core/mapper/xml/*.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wzp_test?serverTimezone=GMT%2B8&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 4096MB
      max-request-size: 4096MB
